<?php

return [
    /*
    |--------------------------------------------------------------------------
    | RSS Feeds Configuration
    |--------------------------------------------------------------------------
    |
    | Add your RSS feed URLs here. The application will fetch articles from
    | these feeds and classify them using the Naive Bayes classifier.
    |
    | You can also map feed URLs to source names for better organization.
    | If a feed URL is not in the mapping, the source name will be extracted
    | from the URL automatically.
    |
    */

    'rss_feeds' => [
        // Original feeds
        'https://feeds.nbcnews.com/nbcnews/public/news',
        'https://abcnews.go.com/abcnews/topstories',
        'https://www.cbsnews.com/latest/rss/main',
        'https://www.vox.com/rss/index.xml',
        'https://feedx.net/rss/ap.xml',
        // New feeds
        'http://thehill.com/rss/syndicator/19110',
        'http://feeds.feedburner.com/DrudgeReportFeed',
        'https://www.chron.com/rss/feed/News-270.php',
        'https://www.theatlantic.com/feed/all/',
        'http://indianexpress.com/section/world/feed/',
        'https://www.sfgate.com/rss/feed/Business-and-Technology-News-448.php',
        'http://variety.com/feed/',
        'http://www.globaltimes.cn/rss/outbrain.xml',
        'http://news.yahoo.com/rss',
        'http://rss.cnn.com/rss/cnn_topstories.rss',
        'http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
        'http://feeds.foxnews.com/foxnews/latest',
        'http://feeds.nbcnews.com/feeds/topstories',
        'http://feeds.washingtonpost.com/rss/business',
        'http://rssfeeds.usatoday.com/usatoday-NewsTopStories',
        'http://www.latimes.com/rss2.0.xml',
        'https://www.yahoo.com/news/rss/finance',
        'http://feeds.bbci.co.uk/news/rss.xml',
        'https://www.theguardian.com/business/economics/rss',
        'http://www.dailymail.co.uk/articles.rss',
        'https://www.forbes.com/real-time/feed2/',
        'https://www.huffingtonpost.com/section/front-page/feed',
        'http://feeds2.feedburner.com/businessinsider',
        'http://www.telegraph.co.uk/rss.xml',
        'http://www.independent.co.uk/rss',
        'http://www.wsj.com/xml/rss/3_7031.xml',
        'http://feeds.reuters.com/reuters/topNews',
        'https://www.cnbc.com/id/100003114/device/rss/rss.html',
        'https://www.investing.com/rss/news.rss',
        'http://time.com/feed/',
        'http://feeds.feedburner.com/daily-express-personal-finance-news',
        'https://www.thesun.co.uk/feed/',
        'https://asia.nikkei.com/rss/feed/nar',
        'http://feeds.mashable.com/Mashable',
        'http://feeds.abcnews.com/abcnews/topstories',
        'https://www.ft.com/?format=rss',
        'http://www.firstpost.com/feed',
        'http://fortune.com/feed/',
        'http://feeds.smh.com.au/rssheadlines/top.xml',
        'http://www.economist.com/sections/economics/rss.xml',
        'https://www.vanityfair.com/feed/rss',
        'http://articlefeeds.nasdaq.com/nasdaq/categories?category=Investing+Ideas',
        'https://feeds.feedburner.com/fastcompany/headlines',
        'http://rss.nzherald.co.nz/rss/xml/nzhtsrsscid_000000698.xml',
        'https://www.theglobeandmail.com/?service=rss&feed=topstories',
        'https://www.space.com/g00/3_c-7x78x78x78.tqbdf.dpn_/c-7NPSFQIFVT34x24iuuqtx3ax2fx2fx78x78x78.tqbdf.dpnx2fipnfx2fgffex2ftjuf.ynm_$/$/$/$?i10c.ua=1',
        'https://www.prnewswire.com/rss/all-news-releases-from-PR-newswire-news.rss',
        'https://www.inverse.com/feed/articles/1.rss',
        'https://www.seccountry.com/feed',
        'https://nextshark.com/feed/',
        'http://business.financialpost.com/feed',
        'http://abc13.com/feed/',
        'http://vancouversun.com/feed',
        'https://www.local10.com/feeds/rssFeed/feedServlet?obfType=GMG_RSS_APP&siteId=800006&categoryId=80041&nbRows=10',
        'http://www.dailynews.com/feed/',
        'http://www.digitaljournal.com/rss/?feed=latest_news',
        'http://www.streetinsider.com/freefeed.php',
        'https://www.profitconfidential.com/feed/',
        'http://reneweconomy.com.au/feed/',
        'http://www.sci-news.com/feed',
        'https://www.eastbayexpress.com/oakland/Rss.xml',
        'https://oracletimes.com/feed/',
        'https://www.thechronicle.com.au/feeds/rss/homepage/',
        'http://www.news-herald.com/section?template=RSS&profile=4000995&mime=xml',
        'http://www.cspdailynews.com/rss',
        'https://utahherald.com/feed',
        'http://dailytelescope.com/feed',
        'https://news4c.com/feed/',
        'http://www.milforddailynews.com/rss',
        'https://solarindustrymag.com/feed',
        'https://www.computerworld.co.nz/rss/tax/news/',
    ],

    /*
    |--------------------------------------------------------------------------
    | Feed Source Name Mapping
    |--------------------------------------------------------------------------
    |
    | Map RSS feed URLs to their source names (e.g., "NBC", "CNN", "BBC").
    | If a feed URL is not mapped here, the source name will be automatically
    | extracted from the URL domain.
    |
    */

    'feed_sources' => [
        // Original feeds
        'https://feeds.nbcnews.com/nbcnews/public/news' => 'NBC',
        'https://abcnews.go.com/abcnews/topstories' => 'ABC',
        'https://www.cbsnews.com/latest/rss/main' => 'CBS',
        'https://www.vox.com/rss/index.xml' => 'Vox',
        'https://feedx.net/rss/ap.xml' => 'Associated Press',
        // New feeds
        'http://thehill.com/rss/syndicator/19110' => 'The Hill',
        'http://feeds.feedburner.com/DrudgeReportFeed' => 'Drudge Report',
        'https://www.chron.com/rss/feed/News-270.php' => 'Houston Chronicle',
        'https://www.theatlantic.com/feed/all/' => 'The Atlantic',
        'http://indianexpress.com/section/world/feed/' => 'Indian Express',
        'https://www.sfgate.com/rss/feed/Business-and-Technology-News-448.php' => 'SF Gate',
        'http://variety.com/feed/' => 'Variety',
        'http://www.globaltimes.cn/rss/outbrain.xml' => 'Global Times',
        'http://news.yahoo.com/rss' => 'Yahoo News',
        'http://rss.cnn.com/rss/cnn_topstories.rss' => 'CNN',
        'http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml' => 'NY Times',
        'http://feeds.foxnews.com/foxnews/latest' => 'Fox News',
        'http://feeds.nbcnews.com/feeds/topstories' => 'NBC',
        'http://feeds.washingtonpost.com/rss/business' => 'Washington Post',
        'http://rssfeeds.usatoday.com/usatoday-NewsTopStories' => 'USA Today',
        'http://www.latimes.com/rss2.0.xml' => 'LA Times',
        'https://www.yahoo.com/news/rss/finance' => 'Yahoo Finance',
        'http://feeds.bbci.co.uk/news/rss.xml' => 'BBC',
        'https://www.theguardian.com/business/economics/rss' => 'The Guardian',
        'http://www.dailymail.co.uk/articles.rss' => 'Daily Mail',
        'https://www.forbes.com/real-time/feed2/' => 'Forbes',
        'https://www.huffingtonpost.com/section/front-page/feed' => 'HuffPost',
        'http://feeds2.feedburner.com/businessinsider' => 'Business Insider',
        'http://www.telegraph.co.uk/rss.xml' => 'Telegraph',
        'http://www.independent.co.uk/rss' => 'Independent',
        'http://www.wsj.com/xml/rss/3_7031.xml' => 'Wall Street Journal',
        'http://feeds.reuters.com/reuters/topNews' => 'Reuters',
        'https://www.cnbc.com/id/100003114/device/rss/rss.html' => 'CNBC',
        'https://www.investing.com/rss/news.rss' => 'Investing.com',
        'http://time.com/feed/' => 'Time',
        'http://feeds.feedburner.com/daily-express-personal-finance-news' => 'Express',
        'https://www.thesun.co.uk/feed/' => 'The Sun',
        'https://asia.nikkei.com/rss/feed/nar' => 'Nikkei',
        'http://feeds.mashable.com/Mashable' => 'Mashable',
        'http://feeds.abcnews.com/abcnews/topstories' => 'ABC',
        'https://www.ft.com/?format=rss' => 'Financial Times',
        'http://www.firstpost.com/feed' => 'Firstpost',
        'http://fortune.com/feed/' => 'Fortune',
        'http://feeds.smh.com.au/rssheadlines/top.xml' => 'Sydney Morning Herald',
        'http://www.economist.com/sections/economics/rss.xml' => 'The Economist',
        'https://www.vanityfair.com/feed/rss' => 'Vanity Fair',
        'http://articlefeeds.nasdaq.com/nasdaq/categories?category=Investing+Ideas' => 'NASDAQ',
        'https://feeds.feedburner.com/fastcompany/headlines' => 'Fast Company',
        'http://rss.nzherald.co.nz/rss/xml/nzhtsrsscid_000000698.xml' => 'NZ Herald',
        'https://www.theglobeandmail.com/?service=rss&feed=topstories' => 'Globe and Mail',
        'https://www.space.com/g00/3_c-7x78x78x78.tqbdf.dpn_/c-7NPSFQIFVT34x24iuuqtx3ax2fx2fx78x78x78.tqbdf.dpnx2fipnfx2fgffex2ftjuf.ynm_$/$/$/$?i10c.ua=1' => 'Space.com',
        'https://www.prnewswire.com/rss/all-news-releases-from-PR-newswire-news.rss' => 'PR Newswire',
        'https://www.inverse.com/feed/articles/1.rss' => 'Inverse',
        'https://www.seccountry.com/feed' => 'SEC Country',
        'https://nextshark.com/feed/' => 'NextShark',
        'http://business.financialpost.com/feed' => 'Financial Post',
        'http://abc13.com/feed/' => 'ABC13',
        'http://vancouversun.com/feed' => 'Vancouver Sun',
        'https://www.local10.com/feeds/rssFeed/feedServlet?obfType=GMG_RSS_APP&siteId=800006&categoryId=80041&nbRows=10' => 'Local 10',
        'http://www.dailynews.com/feed/' => 'Daily News',
        'http://www.digitaljournal.com/rss/?feed=latest_news' => 'Digital Journal',
        'http://www.streetinsider.com/freefeed.php' => 'Street Insider',
        'https://www.profitconfidential.com/feed/' => 'Profit Confidential',
        'http://reneweconomy.com.au/feed/' => 'Renew Economy',
        'http://www.sci-news.com/feed' => 'Sci-News',
        'https://www.eastbayexpress.com/oakland/Rss.xml' => 'East Bay Express',
        'https://oracletimes.com/feed/' => 'Oracle Times',
        'https://www.thechronicle.com.au/feeds/rss/homepage/' => 'The Chronicle',
        'http://www.news-herald.com/section?template=RSS&profile=4000995&mime=xml' => 'News-Herald',
        'http://www.cspdailynews.com/rss' => 'CSP Daily News',
        'https://utahherald.com/feed' => 'Utah Herald',
        'http://dailytelescope.com/feed' => 'Daily Telescope',
        'https://news4c.com/feed/' => 'News4C',
        'http://www.milforddailynews.com/rss' => 'Milford Daily News',
        'https://solarindustrymag.com/feed' => 'Solar Industry',
        'https://www.computerworld.co.nz/rss/tax/news/' => 'Computerworld',
    ],
];

